### ISSUE TITLE
Data already written is cleared from cache with new write request 

### ISSUE THREAD

**Issue by Ruchita7** [westlinkin/CacheUtilsLibrary#3]
In the sample code, since we are saving the data in utf-8 format to a cache file in the device storage, every time a new write request is made, the existing written data is flushed out.

To solve this I appended the content of the file using the FileOutputStream(String path, boolean append) constructor like this  :
            IOUtils.write(fileContent, new FileOutputStream(pathForCacheEntry(fileName),true), ENCODING);

But with this approach the buildGson from JSON for MyClass and Map<String<T>> data types do not work as the data is not in valid JSON format.

**Comment by westlinkin** [comment]
It is intended to flush out the existing written data. To cache data (java object instance) into device, if it uses the same file name, it is meant to be over-write. There is no append-write feature for now.
